### PR TITLE
fix security and arguments

### PR DESCRIPTION
**Pull request by jja**
Thanks for making your test code available! It's helpful.

Here are a few tweaks so we can use our own keys found in the standard places (#1), and specify our own bucket and endpoint (stratus).

See also https://github.com/NCAR/objectstore-examples
It's private for now so I'll have to grant you access individually, if you'd like it.
I have some simple Groovy code there now and we have some simple alternative Python code too that we may add soon.

### CODE REVIEW

**Comment by tcram** [comment]
Hi John,
thanks for catching this.  These are obsolete credentials we used on an object store testbed a while ago, and are no longer valid.

This repo is no longer updated, and I recommend you to instead use our production S3 utility we have developed at [https://github.com/NCAR/isd-s3](url).

- Tom

**Comment by tcram** [comment]
Sorry, here's a correct link: [https://github.com/NCAR/isd-s3](url)

**Comment by tcram** [comment]
Let's try this again: https://github.com/NCAR/isd-s3

**Comment by jja** [comment]
Great, thanks!
Perhaps you can get a link to the new repo inserted into this webpage:
https://www2.cisl.ucar.edu/resources/storage-and-file-systems/object-storage-test-system

**Pull request merged**
